# Artwork.create(name:"Evening at Kuerners", artist:"Andrew Wyeth", url:"https://s31531.pcdn.co/wp-content/uploads/2017/07/EveningAtKuerners_1970_AndrewWyeth_ArtistsNetwork.png", year:"1970")
# Artwork.create(name:"The Hunters in the Snow", artist:"Pieter Bruegel the Elder", url:"https://media.izi.travel/712b0128-72a7-49c8-ae47-06c2adccc4d6/53fd3e2f-6542-4d43-9caf-905b1678eaef_800x600.jpg", year:"1565")
# Artwork.create(name:"Monticello", artist:"Jean-Michel Basquiat", url:"https://uploads2.wikiart.org/images/jean-michel-basquiat/monticello.jpg!Large.jpg", year:"1983")
# Artwork.create(name:"Jenny and Her Sisters are Nearly Run Down by Train...", artist:"Henry Darger", url:"https://d32dm0rphc51dk.cloudfront.net/ue-jUeKBY3GQvrK-t_njTA/large.jpg", year:"no date")
# Artwork.create(name:"Summer Vacation", artist:"Charles Burns", url:"https://i.pinimg.com/736x/a0/95/f9/a095f99e9df30d28a1b065a90b9f3acf.jpg", year:"1995")

# Project.create(name:"MedReady", url:"https://www.youtube.com/embed/yDaJDPpVqiw",partner:"")
# Project.create(name:"Museum", url:"https://www.youtube.com/embed/waPYxd3zV-E", partner:"")
# Project.create(name:"Planetarium", url:"https://www.youtube.com/embed/vZ_1bo70VGA", partner:"Jhanae Chisholm")
Project.create(name:"MedReady2.0", url:"https://www.youtube.com/watch?v=vIXQc8JV61g", partner:"")